In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
print(a[0])

[1 2 3 4]


In [4]:
print(a[2])

[ 9 10 11 12]


In [5]:
a[1,2]

7

In [6]:
a.ndim

2

In [7]:
a.shape

(3, 4)

In [9]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
form1 = ((4, 5))
np.zeros(form1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
ones1 = np.ones((6,2))
print(ones1)

form1 = ((4, 5))
ones2 = np.ones(form1)
print(ones2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
ones3 = np.ones((2,3,2))
ones3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
numbers = np.full((2,4),7, dtype='float')
numbers

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [19]:
empty_array = np.empty(6)
empty_array

array([0., 0., 0., 0., 0., 0.])

In [23]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [24]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [25]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [30]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr_new = np.append(arr,[1,2])
arr_new

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [33]:
arr.shape

(8,)

In [35]:
arr_new.shape

(10,)

In [36]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [38]:
np.delete(arr,6)

array([1, 2, 3, 4, 5, 6, 8])

In [39]:
arr = np.array([2,1,5,3,7,4,6,8])

In [40]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr2d = np.array([[9,18,3,7], [2,1,10,34], [51,0,8,13]])
arr2d

array([[ 9, 18,  3,  7],
       [ 2,  1, 10, 34],
       [51,  0,  8, 13]])

In [42]:
np.sort(arr2d, axis=0)

array([[ 2,  0,  3,  7],
       [ 9,  1,  8, 13],
       [51, 18, 10, 34]])

In [44]:
np.sort(arr2d, axis=1)

array([[ 3,  7,  9, 18],
       [ 1,  2, 10, 34],
       [ 0,  8, 13, 51]])

# Shape and Size

In [45]:
arr2d.shape

(3, 4)

In [46]:
arr2d.ndim #number of dimension

2

In [48]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
 
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                       
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]
                        ])
 
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [51]:
array_example.ndim

3

In [49]:
array_example.shape

(3, 2, 4)

In [50]:
array_example.size

24

In [52]:
array_example.dtype

dtype('int32')

In [54]:
array_example.itemsize 
# 00000000 00000000 00000000 00000000  <-- int32
# 7
# 1110
# 00000000 00000000 00000000 00000000
#                                1110

4

In [56]:
# array_example.astype('int16')
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
 
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                       
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]
                        ], dtype = 'int16')
 
array_example.dtype

dtype('int16')

In [57]:
array_example.itemsize
# 00000000 00000000 <-- int16

2

In [58]:
array_example.nbytes

48

# Reshape

In [59]:
ones3 = np.ones((3,4))
ones3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
ones3.shape

(3, 4)

In [61]:
ones3.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
ones3.reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
ones3.reshape(12,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [64]:
ones3.reshape(1,12)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
ones3.reshape(6,3)  #elemen nya harus sesuai

ValueError: cannot reshape array of size 12 into shape (6,3)

In [66]:
ones3.reshape(2,5) #elemen nya harus sesuai

ValueError: cannot reshape array of size 12 into shape (2,5)

In [67]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [68]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [69]:
a = np.arange(6)
c = a.reshape(2, 3, 1)
c

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [70]:
a = np.arange(18)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [71]:
d = a.reshape(3, 3, 2)
print(d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [72]:
np.reshape(d, (9,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [73]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


# Convert 1D to 2D

In [74]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [75]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [76]:
# for a column vector, You can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Slicing and Indexing

In [77]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [78]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [80]:
five_up = (a>=5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [81]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [83]:
divisible_by_3= (a%3 == 0)
print(a[divisible_by_3])

[ 3  6  9 12]


In [82]:
# You can select elements that satisfy two conditions using the & and | operators

c = a[(a>2)&(a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [84]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
multiple_conditions = ((a > 2) & (a < 11))
a[multiple_conditions]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
random_af = np.random.rand(3,5)
print(random_af)
print(random_af.dtype)

[[0.25394518 0.42731519 0.93785319 0.95436521 0.16284846]
 [0.72071094 0.65192863 0.51443195 0.07815839 0.80055912]
 [0.1187673  0.271002   0.84906737 0.06385516 0.03577841]]
float64


In [87]:
random_af = np.random.rand(5, 1)
print(random_af)

[[0.25880416]
 [0.10375185]
 [0.40231937]
 [0.97537596]
 [0.57667127]]


In [88]:
random_af = np.random.rand(3)
print(random_af)

[0.25996996 0.65057278 0.42945491]


# Creating Array from Existing Data

In [89]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [90]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [92]:
a_1 = np.array([[1,1],[2,2]])
a_1

array([[1, 1],
       [2, 2]])

In [93]:
a_2 = np.array([[3,3],[4,4]])
a_2

array([[3, 3],
       [4, 4]])

In [94]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [95]:
np.vstack((a_1, a_2, a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2]])

In [96]:
np.vstack((a_1, a_2, a_1, a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2],
       [1, 1],
       [2, 2]])

In [97]:
# Or stack them horisontally with hstack
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [98]:
a_3 = np.array([[3, 3, 3],[4, 4, 4]])

In [99]:
np.hstack((a_1, a_2, a_1, a_3))

array([[1, 1, 3, 3, 1, 1, 3, 3, 3],
       [2, 2, 4, 4, 2, 2, 4, 4, 4]])

In [103]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12], [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [104]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [105]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
b[1,1]=10
b

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
c[:, -1]=0
c

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  0],
       [ 9, 10, 11,  0]])

In [111]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [113]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
c

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  0],
       [ 9, 10, 11,  0]])

In [118]:
a+c

array([[ 2,  4,  6,  4],
       [10, 12, 14,  8],
       [18, 20, 22, 12]])

In [119]:
a*c

array([[  1,   4,   9,   0],
       [ 25,  36,  49,   0],
       [ 81, 100, 121,   0]])

In [121]:
a/b

array([[1. , 1. , 1. , 1. ],
       [1. , 0.6, 1. , 1. ],
       [1. , 1. , 1. , 1. ]])

In [122]:
a = np.array([1,2,3,4])
a.sum()

10

In [123]:
a.mean()

2.5

In [125]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [126]:
# You can sum the rows
b.sum(axis=0)

array([3, 3])

In [127]:
# You can sum the columns
b.sum(axis=1)

array([2, 4])

In [128]:
b.mean(axis=0)

array([1.5, 1.5])

In [129]:
data = np.array([1,2])
data

array([1, 2])

In [130]:
data*1.6

array([1.6, 3.2])

In [131]:
data.shape

(2,)

In [ ]:
2x1 * 1x1 ==> 2x1
3x4 * 4x6 ==> 3x6

In [132]:
a3x4 = np.ones((3,4))
a3x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [133]:
a4x6 = np.ones((4,6))
a4x6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# More Array Operations

In [135]:
A = np.array([[0.45053314, 0.1729677, 0.34376245, 0.5510652], [0.54627315, 0.05093587, 0.40067661, 0.55645993], [0.17296772697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.1729677  0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.17296773 0.82485143 0.26590556 0.56917101]]


In [136]:
A.sum()

4.90556977697628

In [137]:
A.min()

0.05093587

In [138]:
A.min(axis=0)

array([0.17296773, 0.05093587, 0.26590556, 0.5510652 ])

In [139]:
A.max()

0.82485143

In [140]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [141]:
A.std()

0.20926780704850073

# Matrices

## Creating Matrices

In [143]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.65166933 0.24285187]
 [0.74695866 0.09077959]
 [0.35229381 0.54492157]]


## Matrix Arithmetic

In [144]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [145]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [146]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [147]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [148]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [150]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [151]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [152]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [153]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [154]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [155]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [156]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [157]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [158]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [159]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [161]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [165]:
ndarr = np.array([[[1,2], [3,4]], 
                  [[5,6], [7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [166]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [167]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [168]:
print(np.random.random((4,3,2)))

[[[0.64340895 0.43269022]
  [0.757927   0.06000874]
  [0.26480467 0.49658922]]

 [[0.73667711 0.40607514]
  [0.13779634 0.68167147]
  [0.80788803 0.79339716]]

 [[0.85623944 0.01060527]
  [0.65229073 0.86728736]
  [0.89276584 0.545992  ]]

 [[0.53699129 0.24970453]
  [0.08512611 0.74430842]
  [0.46264835 0.84356953]]]


# Flatten N-Dimensional Array

In [169]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [170]:
# You can use flatten to flatten your array into a 1D Array

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Working with Math Formulas

In [173]:
n = 30
observed = 20
prediction = 21
error = (1/n)*np.sum(np.square(observed-prediction))
error

0.03333333333333333

# TipsPy

## Notes on Numpy Vector

In [175]:
# Ketika kalian membuat Numpy array dengan command dibawah ini:

a = np.random.rand(5)
print(a)

[0.84732684 0.36631744 0.85394434 0.84253361 0.15704925]


In [176]:
a.shape #Rank 1 Array

(5,)

In [177]:
print(a.T)
#Hasil transpose tidak akan berubah.

[0.84732684 0.36631744 0.85394434 0.84253361 0.15704925]


In [178]:
print(np.dot(a, a.T))
# Hasil operasi dot juga tidak menunjukkan hasil yang seharusnya, karena Rank 1 Array hanya mempunya baris atau kolom saja.

2.3158995306938825


In [179]:
# Tips untuk membuat array adalah selalu masukan 2 argumen ketika akan membuat column ataupun row Vector. Seperti kita memasukkan 5 dan 1 sebagai argumen.

a = np.random.rand(5,1) #column vector
print(a)

[[0.16906971]
 [0.45892114]
 [0.92837597]
 [0.42448093]
 [0.07390902]]


In [180]:
print(a.T)
#Hasil transpose, bentuknya akan berubah

[[0.16906971 0.45892114 0.92837597 0.42448093 0.07390902]]


In [181]:
print(np.dot(a, a.T))
#Hasil operasi dot product sesuai dengan yang seharusnya

[[0.02858457 0.07758966 0.15696026 0.07176687 0.01249578]
 [0.07758966 0.21060861 0.42605136 0.19480327 0.03391841]
 [0.15696026 0.42605136 0.86188194 0.39407789 0.06861536]
 [0.07176687 0.19480327 0.39407789 0.18018406 0.03137297]
 [0.01249578 0.03391841 0.06861536 0.03137297 0.00546254]]


In [182]:
#Begitupula dengan row Vector
a = np.random.rand(1,5) #row Vector
print(a)

[[0.43228009 0.21631713 0.65928219 0.67720122 0.94750565]]


In [183]:
a.shape

(1, 5)

In [ ]:
# Don't use rank 1 Array, always use 1 by n matrices or n by 1 matrices instead (column or row vectors)